name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'
runs:
  # Action Type
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ./custom-action-example-app/node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      working-directory: ./custom-action-example-app
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      # é necessário quando o comando run é usado
      shell: bash