name: Matrix Demo
on: push
jobs:
  build:
    # Continuar a executar os jobs caso algum valor da matrix dê algum erro
    continue-on-error: true
    # Caso queiramos configurar o job com diferentes configurações
    strategy:
      # Irá executar várias vezes esse Job, em paralelo, usando configurações setadas aqui dentro do objeto matrix
      matrix:
        node-version: [12, 14, 16]
        operation-system: [ubuntu-latest, windows-latest]
    # Aplica valores setados no contexto da strategy matrix
    runs-on: ${{ matrix.operation-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          nome-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build