name: Reusable Deploy With Input
on:
  # Adicionando inputs à chamada desse workflow
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        # caso não seja obrigatório, dá para setar um valor padrão
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."