name: Third Workflow - Test and Deploy React Demo
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # primeiro é necessário baixar o nosso código do repositório
      # no serverless do github, onde o runner é executado
      - name: Get code
        # invés de utilizar runs-on e passar os comandos, também é possível
        # utilizar actions já prontas que podem ser encontradas no marketplace
        # do github, por exemplo -> https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3
        #Também é possível encontrar os programas pré-instalados no runner
        # https://docs.github.com/pt/actions/using-github-hosted-runners/about-github-hosted-runners
        # >
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
        # já tem Node instalado, mas também seria possível utilizar uma action do marketplace
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: ./second-action-react-demo
        run: npm ci
      - name: Run tests
        working-directory: ./second-action-react-demo
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./second-action-react-demo
        run: npm ci
      - name: Build project
        working-directory: ./second-action-react-demo
        run: npm run build
      - name: Deploy
        run: echo ˜Deploying ...˜